//--------------------------------------------------------------------------------
// Auto-generated by LiteX (a0330bdbf) on 2026-04-01 16:09:48
//--------------------------------------------------------------------------------
#ifndef __GENERATED_MEM_H
#define __GENERATED_MEM_H

#ifndef WR_WB_SLAVE_BASE
#define WR_WB_SLAVE_BASE 0x00040000L
#define WR_WB_SLAVE_SIZE 0x00040000
#endif

#ifndef CSR_BASE
#define CSR_BASE 0x00000000L
#define CSR_SIZE 0x00020000
#endif

#ifndef MEM_REGIONS
#define MEM_REGIONS "WR_WB_SLAVE  0x00040000 0x40000 \nCSR          0x00000000 0x20000 "
#endif
#endif
